### PR TITLE
Multiple creep mechanisms for CNS and bug fixes

### PR DESCRIPTION
**Pull request by martijnende**
## Features

- CNS model now takes N generic power-law creep mechanisms. These creep mechanisms operate in parallel to one another and to granular flow. This is mainly relevant when the creep rheology changes with depth (temperature), and one creep mechanism starts to dominate over another
- Two new benchmark tests have been added for the CNS model: a velocity-step sequence and low stiffness stick-slip cycles. The simulation outcomes are compared with frozen benchmark results (stored in gzip file)

## Code improvements

- A NaN check has been added to the Runge-Kutta solver routine. When a NaN is encountered, the step size is reduced and integration is continued (re-attempted) rather than allowing NaNs to propagate
- The location of the PyQDYN wrapper is now automatically added to Python examples. The user no longer has to specify its location

## New release proposal

Time to advance to version 1.2?

### CODE REVIEW

**Comment by jpampuero** [comment]
Hi all,
I agree with Martijn, it's a good time for a new release. Scrolling through the commit messages since the last release, I identified the following new features worth mentioning in the release notes:
CNS model, Python wrapper, thermal pressurization, Runge-Kutta solver (Martijn) 
Option to model a fault bisecting a slab of thickness H in 2D, loaded by prescribed uniform displacement along the slab boundaries. (Pablo)
Option to force symmetry of slip with respect to the fault center in 2D simulations. (Pablo)
Binary outputs (Benjamin) 
2018 SCEC benchmark (Benjamin, Yingdi)
Separate inputs for loading velocity (V_PL) and reference friction velocity (V_SS?).

Did I miss anything?

Please make sure the new features you implemented are well documented in the manual before the new release.

**Comment by jpampuero** [comment]
@martijnende, I agree with your suggestions.
@bidini, @ydluo (@bigbigluo), are your new features well documented (binary outputs and SCEC benchmark)?

**Comment by ydluo** [comment]
SCEC benchmark is not yet documented. I will doc it. @jpampuero

**Comment by bidini** [comment]
Hi,

The binary outputs need more testing with other machines. Maybe an implementation of hdf5 outputs would be better so we do not have to worry about how different machines write binary. If you what to release soon, I would not mention it in the documentation and keep it hidden for users until later.

**Comment by martijnende** [comment]
@bidini If we hide this feature from users, there is a risk that they may discover it by themselves and start using it, even though the feature is not stable yet. We could also mention binary outputs as a feature under development ("_use at own risk_"), so that people know it is not yet intended for production, but that it will come soon.

When you decide to continue working on binary outputs, you could create a new branch (e.g. `feature/binary`) and develop/push new code to there. When development/testing is done, you can create a pull request (like this one) and merge it into the stable `master` branch.

As for the output format: I'm a fan/user of HDF5, which also allows for chunked/sliced data processing (i.e. loading the data into memory bit by bit, or just one slice, rather than all in once). This is particularly useful for larger-than-RAM outputs. I'm not too familiar with other data formats.

**Pull request merged**
